(dp1
S'output'
p2
S"<type 'exceptions.ValueError'> invalid literal for long() with base 10: 'u'"
p3
sS'layer'
p4
S'C:\\Users\\Merian Herrera\\Desktop\\web2py\\applications\\super_zapatos\\controllers/services.py'
p5
sS'code'
p6
S'\n@request.restful()\ndef stores():\n    response.view = \'generic.json\'\n    \n    def GET(*args,**vars):\n        pattern = [\n            "/shoes[store]"\n            ]\n        parser = db.parse_as_rest(pattern,args,vars)\n        \n        if parser.status == 200:\n            return dict(stores=parser.response)\n        else:\n            raise HTTP(parser.status,parser.error)\n    return locals()\n\n@request.restful()\ndef articles():\n    response.view = \'generic.json\'\n    \n    def GET(*args,**vars):\n        pattern = [\n            "/shoes[article]",\n            "/stores/{article.store_id}"\n            ]\n        parser = db.parse_as_rest(pattern,args,vars)\n        \n        if parser.status == 200:\n            return dict(success= True, articles=parser.response)\n        else:\n            ##raise HTTP(parser.status,parser.error)\n            return dict(success= False, error=parser.error)\n    return locals()\n\n        \n\nresponse._vars=response._caller(articles)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "gluon/restricted.py", line 221, in restricted\n  File "C:\\Users\\Merian Herrera\\Desktop\\web2py\\applications\\super_zapatos\\controllers/services.py", line 38, in <module>\n  File "gluon/globals.py", line 388, in <lambda>\n  File "gluon/globals.py", line 354, in f\n  File "C:\\Users\\Merian Herrera\\Desktop\\web2py\\applications\\super_zapatos\\controllers/services.py", line 27, in GET\n    parser = db.parse_as_rest(pattern,args,vars)\n  File "gluon/dal.py", line 8341, in parse_as_rest\n  File "gluon/dal.py", line 10714, in count\n  File "gluon/dal.py", line 1894, in count\n  File "gluon/dal.py", line 1881, in _count\n  File "gluon/dal.py", line 1544, in expand\n  File "gluon/dal.py", line 1440, in EQ\n  File "gluon/dal.py", line 1555, in expand\n  File "gluon/dal.py", line 1998, in represent\nValueError: invalid literal for long() with base 10: \'u\'\n'
p11
s.